trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    contents: |
      build/**
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: 'Copy files to artifact staging directory'


- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish build artifacts'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls $(System.DefaultWorkingDirectory)/build
      pwd
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'appservice'
#     appType: 'webAppLinux'
#     appName: 'nodes1122'
#     package: '$(System.DefaultWorkingDirectory)/build'
#     runtimeStack: 'NODE|18-lts'
#     startUpCommand: 'npm start'
#   displayName: 'Deploy to Azure Web App'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'appservice'
    appType: 'webAppLinux'
    WebAppName: 'nodes1122'
    packageForLinux: '$(System.DefaultWorkingDirectory)/build/'
    RuntimeStack: 'NODE|18-lts'
    StartupCommand: 'pm2 serve /home/site/wwwroot --spa --no-daemon'